services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/app/src
    environment:
      - PORT=4000
    command: npm run dev

  client:
    build:
      context: ./client
      target: build
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
      - ./client/index.html:/app/index.html
    environment:
      - VITE_GRAPHQL_URL=http://localhost:4000
    command: npm run dev
    depends_on:
      - server
